#!/bin/bash
#A script to create a file with the date appended to the filename, containing network info

#Create variable DATE containing the current date in MMDDYYYY format
DATE=`date +%m-%d-%y_%R\:%S`

#create a file with the date at the end of the filename
touch netinfo_$DATE

#append output of ip a into the netinfo file
#ip a >> netinfo_$DATE

#create variable DNS containing the current DNS server
DNS=$(dig localhost | awk -F'[ #]' '/SERVER/ {print $3}')

#store IPv4 addresses pulled from ip a in a variable
IPs=$(ip a | awk '/(([0-9]{1,3}\.){3}[0-9]{1,3})/ {print $2}')

#read the listening ports and their associated protocols into 2 variables
listenport=$(ss -tulpn | awk '/LISTEN/ {print $5}' | awk -F: '{print $NF}')
listenprot=$(ss -tulp | awk '/LISTEN/ {print $5}' | awk -F: '{print $NF}')

#append the variables into the netinfo file
echo -e "Primary DNS Server:\n$DNS" >> netinfo_$DATE
echo -e "IPv4 addresses:\n$IPs" >> netinfo_$DATE
echo -e "Listening ports:\n$listenprot" >> netinfo_$DATE
echo -e "Listening protocols:\n$listenport" >> netinfo_$DATE

#concatenate the netinfo file
cat netinfo_$DATE

